# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-27 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axfuser',
            name='u_username',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='用户名'),
        ),
    ]
