# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-28 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_foodtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=255)),
                ('productimg', models.CharField(max_length=255)),
                ('productname', models.CharField(max_length=255)),
                ('productlongname', models.CharField(max_length=255)),
                ('isxf', models.BooleanField(default=True)),
                ('pmdesc', models.BooleanField(default=True)),
                ('specifics', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('marketprice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('categoryid', models.IntegerField()),
                ('childcid', models.IntegerField()),
                ('childcidname', models.CharField(max_length=100)),
                ('dealerid', models.CharField(max_length=30)),
                ('storenums', models.IntegerField()),
                ('productnum', models.IntegerField()),
            ],
        ),
    ]
