# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-28 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_goods_num', models.IntegerField(verbose_name='商品数量')),
                ('c_is_select', models.BooleanField(default=True)),
                ('c_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.AxfUser')),
            ],
        ),
    ]
